apiVersion: apps/v1
kind: Deployment
metadata:
  name: scheduler-consumer
spec:
  replicas: 2
  selector:
    matchLabels:
      app: scheduler-consumer
  template:
    metadata:
      labels:
        app: scheduler-consumer
    spec:
      containers:
      - name: scheduler-consumer
        image: oh20/schedulerconsumer:latest
        envFrom:
        - configMapRef:
            name: healthhelper-config
        - secretRef:
            name: healthhelper-secrets
---
apiVersion: v1
kind: Service
metadata:
  name: scheduler-consumer-service
spec:
  selector:
    app: scheduler-consumer
  ports:
    - port: 80
      targetPort: 80
  type: ClusterIP