apiVersion: v1
kind: Secret
metadata:
  name: healthhelper-secrets
type: Opaque
data:
  ConnectionStrings__DefaultConnection: <base64-encoded-sql-connection>
  RabbitMQ__UserName: <base64-encoded-rabbitmq-user>
  RabbitMQ__Password: <base64-encoded-rabbitmq-password>