apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-register-consumer
spec:
  replicas: 2
  selector:
    matchLabels:
      app: user-register-consumer
  template:
    metadata:
      labels:
        app: user-register-consumer
    spec:
      containers:
      - name: user-register-consumer
        image: oh20/userregisterconsumer:latest
        envFrom:
        - configMapRef:
            name: healthhelper-config
        - secretRef:
            name: healthhelper-secrets
        livenessProbe:
          httpGet:
            path: /health
            port: 80
          initialDelaySeconds: 15
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /health
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 10
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
---
apiVersion: v1
kind: Service
metadata:
  name: user-register-consumer-service
spec:
  selector:
    app: user-register-consumer
  ports:
    - port: 80
      targetPort: 80
  type: ClusterIP