apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-register-producer
spec:
  replicas: 2
  selector:
    matchLabels:
      app: user-register-producer
  template:
    metadata:
      labels:
        app: user-register-producer
    spec:
      containers:
      - name: user-register-producer
        image: oh20/medicosservice:latest
        envFrom:
        - configMapRef:
            name: healthhelper-config
        - secretRef:
            name: healthhelper-secrets
---
apiVersion: v1
kind: Service
metadata:
  name: user-register-producer-service
spec:
  selector:
    app: user-register-producer
  ports:
    - port: 80
      targetPort: 80
  type: LoadBalancer