apiVersion: apps/v1
kind: Deployment
metadata:
  name: appointment-scheduler
spec:
  replicas: 2
  selector:
    matchLabels:
      app: appointment-scheduler
  template:
    metadata:
      labels:
        app: appointment-scheduler
    spec:
      containers:
      - name: appointment-scheduler
        image: oh20/healthhelperproducer:latest
        envFrom:
        - configMapRef:
            name: healthhelper-config
        - secretRef:
            name: healthhelper-secrets
---
apiVersion: v1
kind: Service
metadata:
  name: appointment-scheduler-service
spec:
  selector:
    app: appointment-scheduler
  ports:
    - port: 8080
      targetPort: 8080
  type: LoadBalancer