# producer-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: producer
spec:
  replicas: 2
  selector:
    matchLabels:
      app: producer
  template:
    metadata:
      labels:
        app: producer
    spec:
      containers:
      - name: producer
        image: oh20/healthhelperproducer:latest
        ports:
        - containerPort: 80
        env:
        - name: ASPNETCORE_ENVIRONMENT
          valueFrom:
            configMapKeyRef:
              name: healthhelper-config
              key: ASPNETCORE_ENVIRONMENT
        - name: RabbitMQ__HostName
          valueFrom:
            configMapKeyRef:
              name: healthhelper-config
              key: RabbitMQ__HostName
        - name: RabbitMQ__Port
          valueFrom:
            configMapKeyRef:
              name: healthhelper-config
              key: RabbitMQ__Port
        - name: RabbitMQ__UserName
          valueFrom:
            secretKeyRef:
              name: healthhelper-secrets
              key: RabbitMQ__UserName
        - name: RabbitMQ__Password
          valueFrom:
            secretKeyRef:
              name: healthhelper-secrets
              key: RabbitMQ__Password
        - name: ConsumerServiceUrl
          valueFrom:
            configMapKeyRef:
              name: healthhelper-config
              key: ConsumerServiceUrl