name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [AppoitmentScheduler, HealthHelperAuthSystem, MedicosService, SchedulerConsumer, UserRegisterConsumer]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Docker Image
        run: |
          IMAGE_NAME=seu-usuario/${{ matrix.service }}
          VERSION=$(git rev-parse --short HEAD)
          docker build -t $IMAGE_NAME:$VERSION ./services/${{ matrix.service }}
          docker tag $IMAGE_NAME:$VERSION $IMAGE_NAME:latest
          docker push $IMAGE_NAME:$VERSION
          docker push $IMAGE_NAME:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build
    strategy:
      matrix:
        service: [AppoitmentScheduler, HealthHelperAuthSystem, MedicosService, SchedulerConsumer, UserRegisterConsumer]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set Kubernetes Context (Local)
        run: |
          kubectl config use-context minikube || kubectl config use-context docker-desktop

      - name: Deploy to Local Kubernetes
        run: |
          kubectl set image deployment/${{ matrix.service }}-deployment ${{ matrix.service }}-container=seu-usuario/${{ matrix.service }}:$(git rev-parse --short HEAD)
          kubectl rollout status deployment/${{ matrix.service }}-deployment
