name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Debug - List Directory
        run: ls -R .

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Images
        run: |
          SERVICES=(AppoitmentScheduler HealthHelperAuthSystem MedicosService SchedulerConsumer UserRegisterConsumer)
          for SERVICE in "${SERVICES[@]}"; do
            IMAGE_NAME=oh20/$(echo "$SERVICE" | tr '[:upper:]' '[:lower:]')
            VERSION=$(git rev-parse --short HEAD)
            docker build -t $IMAGE_NAME:$VERSION ./$SERVICE
            docker tag $IMAGE_NAME:$VERSION $IMAGE_NAME:latest
            docker push $IMAGE_NAME:$VERSION
            docker push $IMAGE_NAME:latest
          done

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set Kubernetes Context (Local)
        run: |
          kubectl config use-context minikube || kubectl config use-context docker-desktop

      - name: Deploy to Local Kubernetes
        run: |
          SERVICES=(AppoitmentScheduler HealthHelperAuthSystem MedicosService SchedulerConsumer UserRegisterConsumer)
          for SERVICE in "${SERVICES[@]}"; do
            IMAGE_NAME=seu-usuario/$(echo "$SERVICE" | tr '[:upper:]' '[:lower:]')
            kubectl set image deployment/$SERVICE-deployment $SERVICE-container=$IMAGE_NAME:$(git rev-parse --short HEAD)
            kubectl rollout status deployment/$SERVICE-deployment
          done
