name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  REGISTRY: oh20
  KUBERNETES_NAMESPACE: default
  DEPLOYMENT_TIMEOUT: 300s

jobs:
  validate:
    runs-on: [self-hosted, windows]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Validate directory structure
        shell: pwsh
        run: |
          $ErrorActionPreference = 'Stop'
          $SERVICES = @(
            "AppoitmentScheduler",
            "HealthHelperAuthSystem",
            "MedicosService",
            "SchedulerConsumer",
            "UserRegisterConsumer"
          )
          
          foreach ($SERVICE in $SERVICES) {
            Write-Host "Validating $SERVICE..."
            
            if (-not (Test-Path "./$SERVICE")) {
              Write-Error "Directory ./$SERVICE not found"
              exit 1
            }
            
            if (-not (Test-Path "./$SERVICE/Dockerfile")) {
              Write-Error "Dockerfile not found in ./$SERVICE"
              exit 1
            }
          }
          
          Write-Host "All services validated successfully"

  build:
    needs: validate
    runs-on: [self-hosted, windows]
    strategy:
      matrix:
        service: [
          'appoitmentscheduler',
          'healthhelperauthsystem',
          'medicosservice',
          'schedulerconsumer',
          'userregisterconsumer'
        ]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Get version
        id: get_version
        shell: pwsh
        run: |
          $version = git rev-parse --short HEAD
          echo "VERSION=$version" >> $env:GITHUB_OUTPUT

      - name: Build and push
        shell: pwsh
        run: |
          $ErrorActionPreference = 'Stop'
          $SERVICE = "${{ matrix.service }}"
          $VERSION = "${{ steps.get_version.outputs.VERSION }}"
          $IMAGE_NAME = "${{ env.REGISTRY }}/$SERVICE"
          
          Write-Host "Building $SERVICE..."
          
          docker build -t ${IMAGE_NAME}:${VERSION} ./$SERVICE
          if (-not $?) {
            Write-Error "Docker build failed for $SERVICE"
            exit 1
          }
          
          docker tag ${IMAGE_NAME}:${VERSION} ${IMAGE_NAME}:latest
          
          Write-Host "Pushing $SERVICE images..."
          docker push ${IMAGE_NAME}:${VERSION}
          docker push ${IMAGE_NAME}:latest

  deploy:
    needs: build
    runs-on: [self-hosted, windows]
    env:
      NAMESPACE: default
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Get version
        id: get_version
        shell: pwsh
        run: |
          $version = git rev-parse --short HEAD
          echo "VERSION=$version" >> $env:GITHUB_OUTPUT

      - name: Verify Kubernetes Context
        shell: pwsh
        run: |
          try {
            Write-Host "Attempting to use minikube context..."
            kubectl config use-context minikube
            if (-not $?) {
              Write-Host "Minikube context failed, trying docker-desktop..."
              kubectl config use-context docker-desktop
            }
            
            kubectl get nodes
            if (-not $?) {
              throw "Failed to connect to Kubernetes cluster"
            }
            
            $context = kubectl config current-context
            Write-Host "Successfully connected to Kubernetes context: $context"
          }
          catch {
            Write-Error "Kubernetes context verification failed: $_"
            exit 1
          }

      - name: Apply Kubernetes Configurations
        shell: pwsh
        run: |
          $ErrorActionPreference = 'Stop'
          
          # Definir variáveis com aspas para evitar problemas de parsing
          $VERSION = "${{ steps.get_version.outputs.VERSION }}"
          $NAMESPACE = "default"
          
          # Função para logar com segurança
          function Safe-Log {
            param(
              [string]$Message
            )
            
            if ($Message) {
              try {
                Write-Host $Message
              }
              catch {
                # Fallback logging se Write-Host falhar
                [Console]::WriteLine($Message)
              }
            }
          }
          
          # Função para aplicar configurações
          function Apply-KubernetesConfig {
            param(
              [string]$Path
            )
            
            if (Test-Path $Path) {
              Safe-Log "Applying configurations from $Path..."
              kubectl apply -f $Path
            }
          }
          
          # Aplicar configurações base
          Apply-KubernetesConfig -Path "k8s/RabbitMQ"
          Apply-KubernetesConfig -Path "k8s/config"
          
          # Definir serviços
          $SERVICES = @(
            @{Name="HelHelperUser"; Dir="HelHelperUser"},
            @{Name="HelthHelperAuth"; Dir="HelthHelperAuth"},
            @{Name="HelthHelperConsumer"; Dir="HelthHelperConsumer"},
            @{Name="HelthHelperProducer"; Dir="HelthHelperProducer"}
          )
          
          # Função para processar logs
          function Get-ServiceLogs {
            param(
              [string]$ServiceName,
              [string]$Namespace
            )
            
            # Usar formato de comando direto para evitar interpolação
            $podList = kubectl get pods -l "app=$ServiceName" -n "$Namespace" -o name
            
            foreach ($podResource in $podList) {
              # Remover prefixo 'pod/' se existir
              $currentPod = $podResource -replace '^pod/',''.Trim()
              
              Safe-Log ("Retrieving logs for pod: " + $currentPod)
              
              try {
                $logOutput = kubectl logs "$currentPod" -n "$Namespace" --tail=50 2>&1
                
                if ($logOutput) {
                  Safe-Log ("Logs for " + $currentPod + ":")
                  $logOutput | ForEach-Object { 
                    if ($_) { Safe-Log $_ }
                  }
                }
                else {
                  Safe-Log ("No logs found for pod: " + $currentPod)
                }
              }
              catch {
                Safe-Log ("Error retrieving logs for pod: " + $currentPod + ". Error: " + $_.Exception.Message)
              }
            }
          }
          
          # Processar cada serviço
          foreach ($SERVICE in $SERVICES) {
            $serviceName = $SERVICE.Name
            $serviceDir = $SERVICE.Dir
            
            Safe-Log "Deploying $serviceName..."
            
            try {
              $k8sPath = "k8s/$serviceDir"
              if (-not (Test-Path $k8sPath)) {
                Safe-Log "K8s directory not found for $serviceName at $k8sPath"
                continue
              }
              
              # Processar arquivos YAML
              Get-ChildItem $k8sPath -Filter *.yaml | ForEach-Object {
                $content = Get-Content $_.FullName -Raw
                $updatedContent = $content -replace '(:latest|:v\d+\.\d+\.\d+|:[a-f0-9]+)', ":$VERSION"
                $updatedContent | Set-Content $_.FullName
                
                Safe-Log ("Applying " + $_.Name)
                kubectl apply -f $_.FullName
                
                if (-not $?) {
                  throw "Failed to apply $($_.Name)"
                }
              }
              
              # Verificar deployment
              $deploymentName = "$serviceName-deployment"
              Safe-Log "Waiting for $deploymentName rollout..."
              
              kubectl rollout status deployment/"$deploymentName" `
                -n "$NAMESPACE" `
                --timeout=300s
              
              if (-not $?) {
                throw "Deployment rollout failed"
              }
              
              # Obter logs do serviço
              Get-ServiceLogs -ServiceName $serviceName -Namespace $NAMESPACE
              
              Safe-Log "$serviceName deployment successful"
            }
            catch {
              Safe-Log "Deployment error for $serviceName`: $($_.Exception.Message)"
              
              # Logs de diagnóstico
              Safe-Log "Deployment status:"
              kubectl get deployments -l app="$serviceName" -n "$NAMESPACE"
              
              Safe-Log "Pods status:"
              kubectl get pods -l app="$serviceName" -n "$NAMESPACE"
              
              # Obter logs detalhados em caso de erro
              Get-ServiceLogs -ServiceName $serviceName -Namespace $NAMESPACE
              
              exit 1
            }
          }

      - name: Verify Deployments
        if: success()
        shell: pwsh
        run: |
          $SERVICES = @(
            "HelHelperUser",
            "HelthHelperAuth", 
            "HelthHelperConsumer",
            "HelthHelperProducer"
          )
          $NAMESPACE = "default"

          foreach ($SERVICE in $SERVICES) {
            Safe-Log "Verifying $SERVICE..."
            
            $deployment = kubectl get deployment "$SERVICE-deployment" `
              -n "$NAMESPACE" `
              -o jsonpath='{.status.availableReplicas}'
            
            if ($deployment -lt 1) {
              Write-Error "Deployment $SERVICE does not have any available replicas"
              exit 1
            }
            
            Safe-Log "$SERVICE verification completed successfully"
          }